### ISSUE TITLE
`jsonb` columns serialized as Python object strings

### ISSUE THREAD

**Issue by Destiner** [verifier-alliance/parquet-export#1]
I have trouble accessing `jsonb` column values when importing from parquet files back to Postgres.

Take `compiled_contracts` as an example. In `compiled_contracts/compiled_contracts_0_10000_zstd.parquet`, an entity with id `d8702f97-f056-4380-a9e2-bf5b04913adc` has the following `compilerSettings`:

```
"{'optimizer': {'runs': 200, 'enabled': True}, 'outputSelection': {'Blue_Bull.sol': {'Blue_Bull': ['*']}}}",
```

It's a `string`, and it's also not a valid JSON (e.g. it uses quotes instead of double quotes, `True` instead of `true`).

I don't think it's possible to convert that string back to a valid JSON object, especially if not using Python.

Same thing happens with other `jsonb` columns, both in `compiled_contracts` and `verified_contracts`.

I think the root cause of this is SQLAlchemy serializing JSON columns into python object strings based on the config (e.g. `compiled_settings` [has type](https://github.com/verifier-alliance/parquet-export/blob/main/config.py#L52) `string` there). Changing the type of those columns from `string` to `object` and rerunning the export seems to fix the problem.

**Comment by kuzdogan** [comment]
I think I was able to solve this. Could you please have a look at this example output if it looks good? 

[compiled_contracts_0_100.parquet.txt](https://github.com/user-attachments/files/16179084/compiled_contracts_0_100.parquet.txt)

Just for some reason the job started to run out memory again 🫠 If you have any suggestions there that'd be helpful, I'm not that much literate in pyarrow/pandas.

**Comment by Destiner** [comment]
I think those columns are valid JSON strings now. Thanks!

Re getting OOMed, I think it's because of the table size. It's pretty large even when compressed. I got the same issue with the existing exports for this table specifically. Reducing the number of rows per chunk or per file even more might help.

**Comment by kuzdogan** [comment]
Closing this as I was able to fix this but couldn't publish the exports because of OOM. 

Following the memory leak issue in https://github.com/verifier-alliance/parquet-export/issues/3
