### ISSUE TITLE
Fixing the memory leak in the script

### ISSUE THREAD

**Issue by kuzdogan** [verifier-alliance/parquet-export#3]
When running the script, the job runs out of memory at some point. It seems like some already processed rows stay in memory, even though they are not needed anymore. We need to figure out what's wrong and fix preferably, or come up with a workaround. A workaround might be to run the script for each parquet file again, so the python process starts with fresh memory.

**Comment by kuzdogan** [comment]
Duh, the issue was that we were using the "filesystem" of the container, which actually is a memory-storage on Google CLoud Run instances...

So just mounting an external drive/bucket and saving files there solved the issue. Thanks @manuelwedler

**Comment by manuelwedler** [comment]
I actually solved it by deleting the local files from the in-memory filesystem after uploading. Mounting a bucket could actually save even more memory if we run into issues again.
