### ISSUE TITLE
Set up regular jobs for parquet export on GCP

### ISSUE THREAD

**Issue by manuelwedler** [verifier-alliance/parquet-export#5]
We need to set up the parquet export job on GCP properly. This includes a cron job to run it every night. The set up can be similar to our Sourcify Cloud Run job.

We can already start to run the staging export regularly. Production is not ready yet.

**Comment by manuelwedler** [comment]
Cloud Run jobs and Scheduler jobs have been set up. When #6 is done, I can start exporting staging regularly.

**Comment by manuelwedler** [comment]
Just created the R2 buckets and updated the jobs. Staging is now exported every day to https://export.test.verifieralliance.org/

**Comment by kuzdogan** [comment]
https://export.test.verifieralliance.org/manifest.json gives me a 404

**Comment by manuelwedler** [comment]
This is because the job is still running and didn't complete a full upload yet
