### ISSUE TITLE
R2 export link seems brokern

### ISSUE THREAD

**Issue by arnaudbriche** [verifier-alliance/parquet-export#7]
Hi,

I get a 404 when trying to get ```https://pub-f4b5a1306ebd42a3b1289ab59da1d9bf.r2.dev/manifest.json```

**Comment by kuzdogan** [comment]
Hi

The database with the new v1 schema is still in the making. We'll announce when these new exports are publicly available. 

In the meantime you can play around with Souricfy's exports. It's based on the VerA schema 

https://docs.sourcify.dev/docs/repository/sourcify-database/
